const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
// Use the installed TypeScript compiler; no test framework dependency.
require.extensions['.ts'] = (module, filename) => {
  const source = fs.readFileSync(filename, 'utf8').replaceAll('"@/lib/', '"./');
  module._compile(ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText, filename);
};
const { mockGoals, goalProgress, isGoalComplete, userDailyProgress } = require('./lib/goal-data.ts');
const { deriveToday } = require('./lib/today.ts');
const { levelFromXp } = require('./lib/runtime-data.ts');
const { currentUserId, partnerUserId } = require('./lib/identity.ts');
const { addDays, localDateKey, calendarDaysBetween } = require('./lib/date.ts');
const { mockChallenges, deriveChallengeProgress, challengeRemaining } = require('./lib/challenge-data.ts');
const gym = structuredClone(mockGoals.find(g => g.id === 'gym'));
const study = structuredClone(mockGoals.find(g => g.id === 'study'));
assert.equal(goalProgress(study, { userId: currentUserId, target: 4, currentValue: 2 }), 50);
assert.equal(goalProgress(study, { userId: currentUserId, target: 4, currentValue: -1 }), 0);
assert.equal(isGoalComplete(study, { userId: currentUserId, target: 0, currentValue: 0 }), false);
assert.equal(userDailyProgress([{ ...gym, status: 'paused' }], currentUserId), 0);
assert.equal(userDailyProgress([], currentUserId), 0);
assert.equal(userDailyProgress([study],currentUserId),0);
assert.equal(userDailyProgress([{...study,targets:study.targets.map(target=>target.userId===currentUserId?{...target,currentValue:4}:target)}],currentUserId),100);
const challenge = { ...mockChallenges[0], historyThrough: '2026-09-14' };
assert.deepEqual(deriveChallengeProgress(challenge, gym, '2026-09-15'), { you: 4, friend: 3, shared: 7 });
for (const date of ['2026-09-01', '2026-09-21', '2026-09-14']) assert.deepEqual(deriveChallengeProgress(challenge, gym, date), challenge.historicalProgress);
assert.deepEqual(deriveChallengeProgress({ ...challenge, status: 'completed' }, gym, '2026-09-15'), challenge.historicalProgress);
assert.deepEqual(deriveChallengeProgress(challenge, { ...gym, status: 'paused' }, '2026-09-15'), challenge.historicalProgress);
study.targets = [{ userId: currentUserId, target: 4, currentValue: 4 }, { userId: partnerUserId, target: 3, currentValue: 3 }];
assert.equal(deriveChallengeProgress({ ...challenge, goalType: 'targetDays' }, study, '2026-09-15').shared, 7);
assert.deepEqual(deriveChallengeProgress({ ...challenge, goalType: 'streak', historyThrough: '2026-09-12' }, study, '2026-09-15'), { you: 1, friend: 1, shared: 1 });
assert.equal(challengeRemaining(challenge, '2026-09-20'), 'Ends today');
assert.equal(challengeRemaining(challenge, '2026-09-21'), 'Ended');
assert.equal(addDays('2026-12-31', 1), '2027-01-01');
assert.equal(calendarDaysBetween('2026-03-07', '2026-03-09'), 2);
assert.equal(localDateKey(new Date(2026, 8, 15, 0, 5)), '2026-09-15');
const emptyCompanion={totalXp:0,level:1,levelXp:0,xpForNextLevel:500,currentStreak:0,bestStreak:0,perfectDays:0,accessory:'basic-collar',roomItems:['cozy-bed'],unlockedItems:[],activities:[]};
const before = deriveToday(mockGoals,currentUserId,partnerUserId,emptyCompanion);
const updated = mockGoals.map(g => g.id === 'study' ? study : g);
assert.equal(deriveToday(updated,currentUserId,partnerUserId,emptyCompanion).pet.xp,0);
assert.equal(deriveToday([],currentUserId,partnerUserId,emptyCompanion).perfectDay, false);
assert.deepEqual(levelFromXp(0),{level:1,levelXp:0});
assert.deepEqual(levelFromXp(499),{level:1,levelXp:499});
assert.deepEqual(levelFromXp(500),{level:2,levelXp:0});
console.log('Domain regression checks passed: goals, normalized challenges, snapshots, streak gaps, local dates, ledger XP levels.');
const { createGoalState, selectGoals, setCheckIn, saveGoal } = require('./lib/goal-state.ts');
let state = createGoalState(mockGoals, '2026-09-15');
assert.deepEqual(selectGoals(state).map(goal=>({...goal,targets:goal.targets.map(({hasCheckIn,...target})=>target)})), mockGoals);
assert.equal('currentValue' in state.definitions[0].targets[0], false);
state = setCheckIn(state, 'study', currentUserId, 4);
state = setCheckIn(state, 'study', currentUserId, 4);
assert.equal(state.checkIns.filter(e => e.goalId === 'study' && e.userId === currentUserId && e.date === state.date).length, 1);
assert.equal(selectGoals(state).find(g => g.id === 'study').targets.find(t => t.userId === partnerUserId).currentValue, 1.75);
assert.equal(setCheckIn(state, 'study', currentUserId, Infinity), state);
assert.equal(setCheckIn(state, 'study', 'unknown-user', 2), state);
assert.equal(saveGoal(state, { ...study, name: '   ' }), state);
const tomorrow = { ...state, date: '2026-09-16' };
assert.equal(selectGoals(tomorrow).every(g => g.targets.every(t => t.currentValue === 0)), true);
assert.equal(tomorrow.checkIns.length, state.checkIns.length);
console.log('Dated check-in checks passed: serialization, per-user isolation, idempotent writes, invalid values, day rollover.');
const { isPetItemUnlocked, petAccessories } = require('./lib/pet-data.ts');
assert.equal(isPetItemUnlocked(petAccessories.find(a => a.id === 'oxblood-bandana'), 4, 5), false);
assert.equal(isPetItemUnlocked(petAccessories.find(a => a.id === 'oxblood-bandana'), 5, 5), true);
console.log('Snapshot and level-unlock checks passed.');
